ALTER TABLE "CrmProspect" ADD COLUMN "moduleOneway" BOOLEAN NOT NULL DEFAULT false;

-- Backfill "type de module d'accès" depuis la colonne "Type Module" de
-- l'audit AUDIT_CLIENTS_SESAME_2025.xlsx (jamais renseigné jusqu'ici pour
-- ces champs, ajoutés après l'import initial sans backfill). "Mix" dans
-- l'audit -> moduleSesame ET moduleTtlock tous deux vrais.
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = '1K';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'ACGP93';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'AKANTHA';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'Ambassadeur Lille';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'Appartements de Lille';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'Apparts de Marin';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'ASEAT';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'ASTORG';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'ASTREA';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'AUBERG''INE';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = true, "moduleOneway" = false WHERE "nom" = 'Auberge St Jacques';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = true, "moduleOneway" = false WHERE "nom" = 'Beaujour & Bonsoir';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'Bedzzz Apartments';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'BELLEVAL';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'BUDA FITNESS';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'CHÂTEAU DU SOUZY';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'CITYZEN';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'COEURMANDIE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'COLOMBYA';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'COPWELL – HAVAS';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'COPWELL – LARCO';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'DOJO BORDEAUX';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'DOMAINE DU BELVEDERE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'DYNAMIC SEVRES';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = true, "moduleOneway" = false WHERE "nom" = 'ESCALE AU SOLEIL';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = true, "moduleOneway" = false WHERE "nom" = 'FLORELLA';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'HOTEL MARIE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'KI SPACE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'KUBE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'LA PENICHE AIGUES MORTES';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'LA PENICHE HISSEO';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'LA PENICHE TOURNON';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'LA RUCHE';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'LE BAIN SAUVAGE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'LE VICTOR';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'LES SUITES TOUR EIFFEL';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'LocBox GRANVILLE';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'LocBox VIRE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'LOUVRE PIEMONT';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'LYONNAIS NICE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'MAB BOX';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'MAISON ROQUELONGUE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'MINA MINA';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'MONTEFIORE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'MMIP CITE VERON';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'MMIP CHAMP DE MARS';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'MMIP INVALIDES';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'PUC';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'QUEENS HOTEL PARIS';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'REGINA D''AVIGNON';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'ROSA HOTEL';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = true, "moduleOneway" = false WHERE "nom" = 'ROYAL HOTEL TULLE';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = true, "moduleOneway" = false WHERE "nom" = 'SEROTEL';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'TAC BOX';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'VILLAGE D+ CORREZE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'VILLA CADIERE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'WELLBEE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'YOU ARE DEAUVILLE';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'COPWELL – Fédé. Natation';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'HOTEL DE FRANCE';
UPDATE "CrmProspect" SET "moduleSesame" = false, "moduleTtlock" = false, "moduleOneway" = true WHERE "nom" = 'LocBox AVRANCHES';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'SEM PAU';
UPDATE "CrmProspect" SET "moduleSesame" = true, "moduleTtlock" = false, "moduleOneway" = false WHERE "nom" = 'VILLAGE D+ VALLOIRE';
