-- DataMigration : complète les fiches CrmProspect existantes avec les
-- coordonnées et l'installation issues de l'audit clients Sesame
-- (AUDIT_CLIENTS_SESAME_2025.xlsx, colonnes "Référent du projet", "Interface
-- (PMS)", "Site internet", "Nombre module") — même besoin que la migration
-- 20260817090000 (backfill usage/parcours) : seed.ts n'insère les fiches
-- qu'une seule fois (garde count===0), donc une base déjà provisionnée avant
-- l'ajout de ces valeurs ne les reçoit jamais sans cette correction.
--
-- Chaque champ (référent, téléphone, PMS, site, modules) est mis à jour
-- INDÉPENDAMMENT des autres, chacun gardé uniquement s'il est encore vide
-- (IS NULL / =0) — jamais groupés en une seule UPDATE, pour ne jamais
-- écraser un champ déjà édité manuellement dans l'app juste parce qu'un
-- champ voisin est encore vide.

-- Référent (nom du contact)
UPDATE "CrmProspect" SET "referent"='Ciminato' WHERE "nom"='ASEAT' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Sébastien Besin' WHERE "nom"='Ambassadeur Lille' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Laurent Suys' WHERE "nom"='BUDA FITNESS' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Mathilde Maniglier' WHERE "nom"='Beaujour & Bonsoir' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Damien Verhulst' WHERE "nom"='COEURMANDIE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Laurent Dubernais' WHERE "nom"='COLOMBYA' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Ambre Arena' WHERE "nom"='DYNAMIC SEVRES' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Muriel Thomas' WHERE "nom"='ESCALE AU SOLEIL' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Debora Lemasle' WHERE "nom"='FLORELLA' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Thomas Dunoyer' WHERE "nom"='HOTEL DE LA GARE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='HAMMOUR Areslane' WHERE "nom"='HOTEL MARIE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Pablo Got' WHERE "nom"='KI SPACE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='David Faure' WHERE "nom"='LA PENICHE AIGUES MORTES' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='David Faure' WHERE "nom"='LA PENICHE HISSEO' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='David Faure' WHERE "nom"='LA PENICHE TOURNON' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Roxane CASTEIGNAU' WHERE "nom"='LE BAIN SAUVAGE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Leroy Patricia' WHERE "nom"='LE MEURICE RIVIERA' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='John Paquet' WHERE "nom"='LE VICTOR' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Nathalie Chon' WHERE "nom"='LES SUITES TOUR EIFFEL' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Joeffrey Leduc' WHERE "nom"='LocBox AVRANCHES' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Joeffrey Leduc' WHERE "nom"='LocBox GRANVILLE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Joeffrey Leduc' WHERE "nom"='LocBox VIRE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Mathieu Hontas' WHERE "nom"='MAB BOX' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Nicolas Bonnaud' WHERE "nom"='MINA MINA' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Celine Montefiore' WHERE "nom"='MONTEFIORE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Agathe Gibey' WHERE "nom"='QUEENS HOTEL PARIS' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Thomas LELIEUR' WHERE "nom"='REGINA D''AVIGNON' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Mme Baudry Jambes' WHERE "nom"='SEM PAU' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Johan Ducloux' WHERE "nom"='VILLAGE D+ CORREZE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Johan Ducloux' WHERE "nom"='VILLAGE D+ VALLOIRE' AND "referent" IS NULL;
UPDATE "CrmProspect" SET "referent"='Patrice Arsicaud' WHERE "nom"='WELLBEE' AND "referent" IS NULL;

-- Téléphone
UPDATE "CrmProspect" SET "tel"='01 42 71 20 00' WHERE "nom"='1K' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 65 09 63 89' WHERE "nom"='ASEAT' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 88 83 33 13' WHERE "nom"='Ambassadeur Lille' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='02 43 53 09 68' WHERE "nom"='Apparts de Marin' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='01 85 73 36 45' WHERE "nom"='BELLEVAL' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='+32472889835' WHERE "nom"='BUDA FITNESS' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 79 44 46 76' WHERE "nom"='COEURMANDIE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 84 21 45 00' WHERE "nom"='COLOMBYA' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 74 39 92 15' WHERE "nom"='DOJO BORDEAUX' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 08 84 02 29' WHERE "nom"='DYNAMIC SEVRES' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='04 94 52 71 47' WHERE "nom"='ESCALE AU SOLEIL' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='04 22 32 62 53' WHERE "nom"='FLORELLA' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='01 47 05 40 49' WHERE "nom"='HOTEL DE FRANCE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='03 85 52 17 90' WHERE "nom"='HOTEL DE LA GARE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 27 68 42 10' WHERE "nom"='HOTEL MARIE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 98 79 80 12' WHERE "nom"='KI SPACE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 07 40 10 24' WHERE "nom"='LA PENICHE AIGUES MORTES' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 07 40 10 24' WHERE "nom"='LA PENICHE HISSEO' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 07 40 10 24' WHERE "nom"='LA PENICHE TOURNON' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='01 30 33 20 00' WHERE "nom"='LA RUCHE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 87 28 43 84' WHERE "nom"='LE BAIN SAUVAGE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 68 89 38 98' WHERE "nom"='LE MEURICE RIVIERA' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 42 45 36 95' WHERE "nom"='LE VICTOR' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 09 17 56 01' WHERE "nom"='LES SUITES TOUR EIFFEL' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 50 94 83 17' WHERE "nom"='LocBox AVRANCHES' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 50 94 83 17' WHERE "nom"='LocBox GRANVILLE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 50 94 83 17' WHERE "nom"='LocBox VIRE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 71 39 42 87' WHERE "nom"='MAB BOX' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='04 22 46 03 03' WHERE "nom"='MONTEFIORE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 07 30 69 99' WHERE "nom"='QUEENS HOTEL PARIS' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 61 47 88 05' WHERE "nom"='REGINA D''AVIGNON' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='06 75 66 36 39' WHERE "nom"='SEM PAU' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='0672613185' WHERE "nom"='VILLAGE D+ CORREZE' AND "tel" IS NULL;
UPDATE "CrmProspect" SET "tel"='0672613185' WHERE "nom"='VILLAGE D+ VALLOIRE' AND "tel" IS NULL;

-- PMS
UPDATE "CrmProspect" SET "pms"='Mews Intégration' WHERE "nom"='1K' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='AKANTHA' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='TeamR' WHERE "nom"='ASEAT' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MyGuest Check' WHERE "nom"='ASTORG' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='AUBERG''INE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MisterBooking' WHERE "nom"='Ambassadeur Lille' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Chloé' WHERE "nom"='Apparts de Marin' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MisterBooking' WHERE "nom"='Auberge St Jacques' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Mews Intégration' WHERE "nom"='BELLEVAL' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='Beaujour & Bonsoir' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MyGuest Check' WHERE "nom"='CITYZEN' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Mews Intégration' WHERE "nom"='COEURMANDIE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='TeamR' WHERE "nom"='DOJO BORDEAUX' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='TeamR' WHERE "nom"='DYNAMIC SEVRES' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Reservit' WHERE "nom"='ESCALE AU SOLEIL' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Mews Intégration' WHERE "nom"='FLORELLA' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='HOTEL DE FRANCE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='HOTEL DE LA GARE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='HOTEL MARIE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Mews Intégration' WHERE "nom"='KI SPACE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Mews Intégration' WHERE "nom"='KUBE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MisterBooking' WHERE "nom"='LA PENICHE AIGUES MORTES' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MisterBooking' WHERE "nom"='LA PENICHE TOURNON' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='LE BAIN SAUVAGE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Medialog' WHERE "nom"='LE MEURICE RIVIERA' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Lodgify' WHERE "nom"='LE VICTOR' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MisterBooking' WHERE "nom"='LES SUITES TOUR EIFFEL' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MisterBooking' WHERE "nom"='LOUVRE PIEMONT' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='LYONNAIS NICE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Easy Space' WHERE "nom"='LocBox AVRANCHES' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Easy Space' WHERE "nom"='LocBox GRANVILLE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Easy Space' WHERE "nom"='LocBox VIRE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Escobe' WHERE "nom"='MAISON ROQUELONGUE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='MINA MINA' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Médialog' WHERE "nom"='MMIP CHAMP DE MARS' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Médialog' WHERE "nom"='MMIP CITE VERON' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Medialog' WHERE "nom"='MMIP INVALIDES' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Mews Intégration' WHERE "nom"='MONTEFIORE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='TeamR' WHERE "nom"='PUC' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Medialog' WHERE "nom"='QUEENS HOTEL PARIS' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Medialog' WHERE "nom"='REGINA D''AVIGNON' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MisterBooking' WHERE "nom"='ROSA HOTEL' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='MisterBooking' WHERE "nom"='ROYAL HOTEL TULLE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Medialog' WHERE "nom"='SEROTEL' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Thais' WHERE "nom"='VILLAGE D+ VALLOIRE' AND "pms" IS NULL;
UPDATE "CrmProspect" SET "pms"='Mews Intégration' WHERE "nom"='YOU ARE DEAUVILLE' AND "pms" IS NULL;

-- Site web
UPDATE "CrmProspect" SET "site"='1k-paris.com' WHERE "nom"='1K' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='residence-akantha.nicehotelnice.com' WHERE "nom"='AKANTHA' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='aseat.fr' WHERE "nom"='ASEAT' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotel-astrea-nevers.fr' WHERE "nom"='ASTREA' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='maisons-glenn-anna.fr' WHERE "nom"='AUBERG''INE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotel-lille-ambassadeur.fr' WHERE "nom"='Ambassadeur Lille' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='appartementsdelille.com' WHERE "nom"='Appartements de Lille' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='marin-hotel.fr' WHERE "nom"='Apparts de Marin' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='aubergestjacques.fr' WHERE "nom"='Auberge St Jacques' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='belleval-hotel-paris.com' WHERE "nom"='BELLEVAL' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='beaujour-bonsoir.fr' WHERE "nom"='Beaujour & Bonsoir' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='bedzzz.com' WHERE "nom"='Bedzzz Apartments' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='chateaudusouzy.com' WHERE "nom"='CHÂTEAU DU SOUZY' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='domaine-de-coeurmandie.fr' WHERE "nom"='COEURMANDIE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='dojobordeauxmetropole.com' WHERE "nom"='DOJO BORDEAUX' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='domainedubelvedere.com' WHERE "nom"='DOMAINE DU BELVEDERE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='dynamicsevres.com' WHERE "nom"='DYNAMIC SEVRES' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotelescalesoleil.com' WHERE "nom"='ESCALE AU SOLEIL' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='florella.fr' WHERE "nom"='FLORELLA' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hoteldefrance.com' WHERE "nom"='HOTEL DE FRANCE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='delagare.hotel-autun.fr' WHERE "nom"='HOTEL DE LA GARE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotelmarie.fr' WHERE "nom"='HOTEL MARIE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='kispace-hotel.com/fr' WHERE "nom"='KI SPACE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='kubehotel-paris.com' WHERE "nom"='KUBE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='lapeniche.biz' WHERE "nom"='LA PENICHE AIGUES MORTES' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='lapeniche.biz' WHERE "nom"='LA PENICHE HISSEO' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='lapeniche.biz' WHERE "nom"='LA PENICHE TOURNON' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotel-laruche78.com' WHERE "nom"='LA RUCHE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='lebainsauvage-pyrenees.com' WHERE "nom"='LE BAIN SAUVAGE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotel-le-meurice.com' WHERE "nom"='LE MEURICE RIVIERA' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='levictor-paris.com' WHERE "nom"='LE VICTOR' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='aucoeurparis.com/hotel-au-coeur-de-republique' WHERE "nom"='LES SUITES TOUR EIFFEL' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotel-louvre-piemont.com' WHERE "nom"='LOUVRE PIEMONT' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotel-lyonnais-nice.pensionaussie.top' WHERE "nom"='LYONNAIS NICE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='loc-box.com' WHERE "nom"='LocBox AVRANCHES' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='loc-box.com' WHERE "nom"='LocBox GRANVILLE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='loc-box.com' WHERE "nom"='LocBox VIRE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='maison-roquelongue.fr' WHERE "nom"='MAISON ROQUELONGUE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='minamina-chambreavecjacuzziprivatif.com' WHERE "nom"='MINA MINA' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='mymaisoninparis.com' WHERE "nom"='MMIP CHAMP DE MARS' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='mymaisoninparis.com' WHERE "nom"='MMIP CITE VERON' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='mymaisoninparis.com' WHERE "nom"='MMIP INVALIDES' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='montefiore-apartments.com' WHERE "nom"='MONTEFIORE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='puc.paris' WHERE "nom"='PUC' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='queens-hotel-paris.com' WHERE "nom"='QUEENS HOTEL PARIS' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotelregina-avignon.fr' WHERE "nom"='REGINA D''AVIGNON' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='rosa-hotel.com' WHERE "nom"='ROSA HOTEL' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='leroyal-hotel.com' WHERE "nom"='ROYAL HOTEL TULLE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='paucitemultimedia.com' WHERE "nom"='SEM PAU' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='hotellutece.com' WHERE "nom"='SEROTEL' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='tacbox.fr' WHERE "nom"='TAC BOX' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='village-dplus.com/fr/detente-correze' WHERE "nom"='VILLAGE D+ CORREZE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='pulse-sports-agency.com' WHERE "nom"='VILLAGE D+ VALLOIRE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='wellbeespace.fr' WHERE "nom"='WELLBEE' AND "site" IS NULL;
UPDATE "CrmProspect" SET "site"='youaredeauville.com' WHERE "nom"='YOU ARE DEAUVILLE' AND "site" IS NULL;

-- Nombre de modules
UPDATE "CrmProspect" SET "modules"=51 WHERE "nom"='1K' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=7 WHERE "nom"='ACGP93' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=6 WHERE "nom"='AKANTHA' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=4 WHERE "nom"='ASEAT' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=36 WHERE "nom"='ASTORG' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=24 WHERE "nom"='AUBERG''INE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=30 WHERE "nom"='Ambassadeur Lille' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=8 WHERE "nom"='Appartements de Lille' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=2 WHERE "nom"='Apparts de Marin' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=14 WHERE "nom"='Auberge St Jacques' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=67 WHERE "nom"='BELLEVAL' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=1 WHERE "nom"='BUDA FITNESS' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=36 WHERE "nom"='Beaujour & Bonsoir' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=42 WHERE "nom"='Bedzzz Apartments' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=9 WHERE "nom"='CHÂTEAU DU SOUZY' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=24 WHERE "nom"='CITYZEN' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=27 WHERE "nom"='COEURMANDIE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=3 WHERE "nom"='COLOMBYA' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=2 WHERE "nom"='COPWELL – Fédé. Natation' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=5 WHERE "nom"='COPWELL – HAVAS' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=1 WHERE "nom"='COPWELL – LARCO' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=1 WHERE "nom"='DOJO BORDEAUX' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=3 WHERE "nom"='DOMAINE DU BELVEDERE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=2 WHERE "nom"='DYNAMIC SEVRES' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=17 WHERE "nom"='ESCALE AU SOLEIL' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=17 WHERE "nom"='FLORELLA' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=61 WHERE "nom"='HOTEL DE FRANCE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=22 WHERE "nom"='HOTEL DE LA GARE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=25 WHERE "nom"='HOTEL MARIE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=43 WHERE "nom"='KUBE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=8 WHERE "nom"='LA PENICHE AIGUES MORTES' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=4 WHERE "nom"='LA PENICHE HISSEO' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=11 WHERE "nom"='LA PENICHE TOURNON' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=17 WHERE "nom"='LA RUCHE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=18 WHERE "nom"='LE BAIN SAUVAGE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=23 WHERE "nom"='LE MEURICE RIVIERA' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=11 WHERE "nom"='LE VICTOR' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=12 WHERE "nom"='LES SUITES TOUR EIFFEL' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=22 WHERE "nom"='LOUVRE PIEMONT' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=31 WHERE "nom"='LYONNAIS NICE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=2 WHERE "nom"='LocBox AVRANCHES' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=2 WHERE "nom"='LocBox GRANVILLE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=4 WHERE "nom"='LocBox VIRE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=2 WHERE "nom"='MAB BOX' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=1 WHERE "nom"='MAISON ROQUELONGUE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=3 WHERE "nom"='MINA MINA' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=6 WHERE "nom"='MMIP CHAMP DE MARS' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=19 WHERE "nom"='MMIP CITE VERON' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=54 WHERE "nom"='MMIP INVALIDES' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=7 WHERE "nom"='MONTEFIORE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=5 WHERE "nom"='PUC' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=19 WHERE "nom"='QUEENS HOTEL PARIS' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=29 WHERE "nom"='REGINA D''AVIGNON' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=35 WHERE "nom"='ROSA HOTEL' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=27 WHERE "nom"='ROYAL HOTEL TULLE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=18 WHERE "nom"='SEM PAU' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=17 WHERE "nom"='SEROTEL' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=2 WHERE "nom"='TAC BOX' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=5 WHERE "nom"='VILLA CADIERE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=29 WHERE "nom"='VILLAGE D+ CORREZE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=45 WHERE "nom"='VILLAGE D+ VALLOIRE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=56 WHERE "nom"='WELLBEE' AND "modules"=0;
UPDATE "CrmProspect" SET "modules"=94 WHERE "nom"='YOU ARE DEAUVILLE' AND "modules"=0;